import { GroceryProduct, GroceryCategory, ExclusiveDeal } from '../types/store';

export const SAMPLE_CATEGORIES: GroceryCategory[] = [
  { id: '1', name: 'Fruits & Vegetables', icon: '🍎' },
  { id: '2', name: 'Meat & Seafood', icon: '🥩' },
  { id: '3', name: 'Dairy Products', icon: '🥛' },
  { id: '4', name: 'Frozen Foods', icon: '🍦' },
  { id: '5', name: 'Snacks', icon: '🍟' },
  { id: '6', name: 'Beverages', icon: '🥤' },
  { id: '7', name: 'Bakery', icon: '🥐' },
  { id: '8', name: 'Instant Noodles', icon: '🍜' },
  { id: '9', name: 'Rice & Grains', icon: '🌾' },
  { id: '10', name: 'Breakfast Items', icon: '🥣' },
  { id: '11', name: 'Condiments & Sauces', icon: '🥫' },
  { id: '12', name: 'Personal Care', icon: '🧴' },
  { id: '13', name: 'Household Essentials', icon: '🧹' },
  { id: '14', name: 'Baby Products', icon: '👶' },
  { id: '15', name: 'Pet Supplies', icon: '🐕' },
  { id: '16', name: 'Organic Products', icon: '🌿' },
];

export const SAMPLE_PRODUCTS: GroceryProduct[] = [
  {
    id: 'p1',
    name: 'Fresh Bananas',
    brand: 'Nature Choice',
    category: 'Fruits & Vegetables',
    price: 2.99,
    unit: '1kg',
    image: 'https://images.unsplash.com/photo-1571771894821-ad9902537327?auto=format&fit=crop&w=400',
    inStock: true,
    stockCount: 50,
    deliveryEta: '30 mins',
    rating: 4.8,
    reviewsCount: 124,
    isBestseller: true
  },
  {
    id: 'p2',
    name: 'Large Brown Eggs',
    brand: 'Golden Farm',
    category: 'Dairy Products',
    price: 5.50,
    originalPrice: 6.50,
    discount: 15,
    unit: '12pcs',
    image: 'https://images.unsplash.com/photo-1518562144211-12c8751dbd66?auto=format&fit=crop&w=400',
    inStock: true,
    stockCount: 20,
    deliveryEta: '25 mins',
    rating: 4.9,
    reviewsCount: 342,
    isBestseller: true,
    isFlashSale: true
  },
  {
    id: 'p3',
    name: 'Chicken Breast',
    brand: 'Fresh Cuts',
    category: 'Meat & Seafood',
    price: 8.99,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=400',
    inStock: true,
    stockCount: 15,
    deliveryEta: '40 mins',
    rating: 4.7,
    reviewsCount: 89
  },
  {
    id: 'p4',
    name: 'Coca-Cola 1.5L',
    brand: 'Coca-Cola',
    category: 'Beverages',
    price: 1.99,
    unit: '1.5L',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&w=400',
    inStock: true,
    stockCount: 100,
    deliveryEta: '20 mins',
    rating: 4.5,
    reviewsCount: 1200,
    isFlashSale: true
  },
  {
    id: 'p5',
    name: 'Premium Jasmine Rice',
    brand: 'Golden Harvest',
    category: 'Rice & Grains',
    price: 12.50,
    unit: '5kg',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400',
    inStock: true,
    stockCount: 30,
    deliveryEta: '45 mins',
    rating: 4.9,
    reviewsCount: 210,
    isOrganic: true
  },
  {
    id: 'p6',
    name: 'Vanilla Ice Cream',
    brand: 'Selecta',
    category: 'Frozen Foods',
    price: 4.99,
    unit: '1.5L',
    image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=400',
    inStock: true,
    stockCount: 12,
    deliveryEta: '35 mins',
    rating: 4.6,
    reviewsCount: 78
  },
  {
    id: 'p7',
    name: 'Pancit Canton Extra Hot',
    brand: 'Lucky Me',
    category: 'Instant Noodles',
    price: 0.50,
    unit: '80g',
    image: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=400',
    inStock: true,
    stockCount: 200,
    deliveryEta: '15 mins',
    rating: 4.9,
    reviewsCount: 5200,
    isBestseller: true
  },
  {
    id: 'p8',
    name: 'Organic Kale',
    brand: 'Garden Fresh',
    category: 'Organic Products',
    price: 3.50,
    unit: '250g',
    image: 'https://images.unsplash.com/photo-1524179091875-bf99a9a6af97?auto=format&fit=crop&w=400',
    inStock: true,
    stockCount: 15,
    deliveryEta: '30 mins',
    rating: 4.8,
    reviewsCount: 45,
    isOrganic: true
  }
];

export const SAMPLE_EXCLUSIVES: ExclusiveDeal[] = [
  {
    id: 'e1',
    title: 'Japanese Wagyu Beef',
    description: 'A5 Grade Wagyu beef imported directly from Hokkaido. Known for its intense marbling and melt-in-your-mouth texture.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200',
    category: 'Premium Meat',
    discount: 20,
    rating: 5.0,
    reviews: 124,
    limitedStock: true,
    endsAt: Date.now() + 3600000 * 24,
    isVipOnly: false,
    badge: 'EXCLUSIVE'
  },
  {
    id: 'e2',
    title: 'Korean Premium Snack Box',
    description: 'A curated selection of the most popular and rare snacks from South Korea. Limited monthly edition.',
    image: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?auto=format&fit=crop&w=800',
    category: 'Imported Snacks',
    discount: 10,
    rating: 4.8,
    reviews: 89,
    limitedStock: false,
    endsAt: Date.now() + 3600000 * 48,
    isVipOnly: true,
    badge: 'VIP ACCESS'
  },
  {
    id: 'e3',
    title: 'Vintage Bordeaux 2015',
    description: 'A rich, complex red wine with notes of dark berries and subtle oak. Perfect for celebratory dinners.',
    image: 'https://images.unsplash.com/photo-1510850478974-bc23a9503fe2?auto=format&fit=crop&w=800',
    category: 'Wine & Spirits',
    discount: 15,
    rating: 4.9,
    reviews: 56,
    limitedStock: true,
    endsAt: Date.now() + 3600000 * 72,
    isVipOnly: true,
    badge: 'PREMIUM'
  }
];
